"""
Capture demo screenshots of the Agentic Wealth Copilot UI.

Story arc  (16 shots, DemoMicrosoftEmployee only):
  Act 1 — Income & Tax pipeline   01-08   Document ingestion → parse → validation → paystub JSON → W-2 JSON → trends → AI insights
  Act 2 — Spending                09-10   2018 full-year categorised expenses + analytics
  Act 3 — Wealth & Planning       11-12   Asset entry + net-worth summary
  Act 4 — Investing & Trading     13-15   Watchlist → stock suggestions → index education
  Act 5 — Copilot (conclusion)    16      Ask tax + spending question, get cross-module AI answer

  Note: shots 05 (parsed_paystub_schema) and 06 (parsed_w2_schema) are static images
        generated by scripts/generate_json_schema_screenshot.py — not captured from the UI.

Usage:
    .venv/bin/python scripts/take_screenshots.py

Requires:
    Backend  running at http://127.0.0.1:8000
    Frontend running at http://localhost:8501
    playwright + chromium:
        .venv/bin/pip install playwright
        .venv/bin/playwright install chromium
"""

import asyncio
import os
import shutil
from pathlib import Path

from PIL import Image
from playwright.async_api import async_playwright, Page

BASE     = "http://localhost:8501"
OUT_DIR  = Path(__file__).parent.parent / "demo" / "screenshots"
VIEWPORT = {"width": 1440, "height": 900}

DEMO_PERSON = "DemoMicrosoftEmployee"


# ── helpers ───────────────────────────────────────────────────────────────────

async def go(page: Page, path: str = "/", wait_ms: int = 4500) -> None:
    """Navigate to a Streamlit page and wait for it to finish rendering."""
    url = BASE if path in ("/", "") else f"{BASE}/{path.lstrip('/')}"
    await page.goto(url, wait_until="networkidle")
    # Dismiss any Streamlit 404 / error dialog
    esc_target = page.locator('[data-testid="stModal"] button, button[aria-label="Close"]')
    if await esc_target.count():
        await esc_target.first.click()
        await page.wait_for_timeout(600)
    await page.wait_for_timeout(wait_ms)


async def shot(page: Page, name: str, *, full_page: bool = True) -> None:
    path = OUT_DIR / name
    await page.screenshot(path=str(path), full_page=full_page)
    print(f"  ✓  {name}")


async def shot_viewport(page: Page, name: str) -> None:
    await shot(page, name, full_page=False)


async def scroll_to(page: Page, y: int, settle_ms: int = 1200) -> None:
    await page.evaluate(f"window.scrollTo(0, {y})")
    await page.wait_for_timeout(settle_ms)


async def scroll_bottom(page: Page, settle_ms: int = 1500) -> None:
    await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
    await page.wait_for_timeout(settle_ms)


async def select_person(page: Page, person: str, timeout: int = 8000) -> None:
    await page.wait_for_selector('[data-testid="stSelectbox"]', timeout=timeout)
    box = page.locator('[data-testid="stSelectbox"]').first
    await box.click()
    await page.wait_for_timeout(300)
    await page.get_by_role("option", name=person).first.click()
    await page.wait_for_timeout(2500)


async def click_button(page: Page, label: str, wait_ms: int = 0) -> bool:
    """Click a button by label (partial text match, works with emoji prefixes)."""
    btn = page.locator("button", has_text=label)
    if await btn.count():
        await btn.first.scroll_into_view_if_needed()
        await btn.first.click()
        if wait_ms:
            await page.wait_for_timeout(wait_ms)
        return True
    return False


async def expand(page: Page, text: str) -> bool:
    """Click an st.expander by its label text."""
    el = page.get_by_text(text, exact=False).first
    if await el.count():
        await el.click()
        await page.wait_for_timeout(800)
        return True
    return False


# ── story acts ────────────────────────────────────────────────────────────────

async def act1_income_pipeline(page: Page) -> None:
    """
    Act 1 — Income & Tax Data Pipeline
    Document ingestion → parsing → invariant validation → AI insights.
    Shows how raw PDFs (paystubs + W-2) are scanned, parsed, and validated.
    """
    print("\nAct 1 — Income & Tax pipeline")

    # ── Shot 01: Income & Tax page — document ingestion overview ─────────────
    await go(page, "Income_%26_Tax", wait_ms=4500)
    try:
        await select_person(page, DEMO_PERSON)
    except Exception:
        pass
    await scroll_to(page, 0)
    await shot(page, "01_income_document_ingestion.png")

    # ── Shot 02: Paystub summary — load trends then scroll to the table ──────
    loaded = await click_button(page, "Load Trends Now")
    if loaded:
        await page.wait_for_timeout(5000)
    # Scroll to "Individual Paystubs" header so the summary table is visible
    paystub_header = page.locator("text=Individual Paystubs").first
    if await paystub_header.count():
        await paystub_header.scroll_into_view_if_needed()
        await page.wait_for_timeout(1000)
    else:
        await scroll_to(page, 600)
    await shot_viewport(page, "02_income_paystub_summary.png")

    # Load trends fresh so the drilldown renders
    await go(page, "Income_%26_Tax", wait_ms=3500)
    try:
        await select_person(page, DEMO_PERSON)
    except Exception:
        pass
    await scroll_to(page, 0, settle_ms=500)
    loaded = await click_button(page, "Load Trends Now")
    if loaded:
        await page.wait_for_timeout(5000)

    # ── Shot 03: tall-viewport approach — all content visible, no scroll offset ──
    # Set viewport to 3000 px tall so Streamlit renders all rows without scrolling.
    # getBoundingClientRect() then gives true absolute coords (scrollY stays 0).
    # PIL-crop the drilldown section from the screenshot.
    drilldown_el = page.locator("text=Paystub Details").first
    if await drilldown_el.count():
        await page.set_viewport_size({"width": 1440, "height": 3000})
        await page.wait_for_timeout(2000)   # let Streamlit re-render at new height

        start_y = await page.evaluate(r"""() => {
            const all = Array.from(document.querySelectorAll('*'));
            const el = all.find(e =>
                /Paystub Details \(Drill-Down\)/.test(e.textContent.trim())
                && e.children.length === 0);
            if (!el) return null;
            const r = el.getBoundingClientRect();
            return Math.max(0, r.top - 16);
        }""")
        end_y = await page.evaluate(r"""() => {
            const all = Array.from(document.querySelectorAll('*'));
            const posts = all.filter(e =>
                /^✅ Post: \$/.test(e.textContent.trim()) && e.children.length === 0);
            if (!posts.length) return null;
            const last = posts[posts.length - 1];
            const r = last.getBoundingClientRect();
            return r.bottom + 20;
        }""")
        print(f"  Drilldown crop: y_start={start_y}  y_end={end_y}")

        if start_y is not None and end_y is not None and end_y > start_y:
            tmp = OUT_DIR / "_tmp_full.png"
            await page.screenshot(path=str(tmp))   # viewport (3000 px tall)
            img = Image.open(tmp)
            print(f"  Viewport size: {img.size}")
            cropped = img.crop((0, int(start_y), img.width, int(end_y)))
            cropped.save(str(OUT_DIR / "03_income_paystub_drilldown.png"))
            tmp.unlink()
            print("  ✓  03_income_paystub_drilldown.png")
        else:
            await shot_viewport(page, "03_income_paystub_drilldown.png")

        await page.set_viewport_size(VIEWPORT)   # restore
    else:
        await shot_viewport(page, "03_income_paystub_drilldown.png")

    # ── Shot 04: Validation checks explained (expander expanded) ─────────────
    # The expander is on the same trends-loaded page; scroll back up to find it.
    val_expander = page.get_by_text("Validation Checks Explained", exact=False).first
    if await val_expander.count():
        await val_expander.scroll_into_view_if_needed()
        await page.wait_for_timeout(500)
        await val_expander.click()
        await page.wait_for_timeout(1200)

        await page.set_viewport_size({"width": 1440, "height": 3000})
        await page.wait_for_timeout(1500)

        start_y = await page.evaluate(r"""() => {
            const all = Array.from(document.querySelectorAll('*'));
            const el = all.find(e =>
                /Validation Checks Explained/.test(e.textContent.trim())
                && e.children.length === 0);
            if (!el) return null;
            const r = el.getBoundingClientRect();
            return Math.max(0, r.top - 12);
        }""")
        end_y = await page.evaluate(r"""() => {
            const all = Array.from(document.querySelectorAll('*'));
            const els = all.filter(e =>
                /Legal services/.test(e.textContent.trim())
                && e.children.length === 0);
            if (!els.length) return null;
            const last = els[els.length - 1];
            const r = last.getBoundingClientRect();
            return r.bottom + 32;
        }""")
        print(f"  Validation crop: y_start={start_y}  y_end={end_y}")

        if start_y is not None and end_y is not None and end_y > start_y:
            tmp = OUT_DIR / "_tmp_full.png"
            await page.screenshot(path=str(tmp))
            img = Image.open(tmp)
            cropped = img.crop((0, int(start_y), img.width, int(end_y)))
            cropped.save(str(OUT_DIR / "04_income_paystub_validation.png"))
            tmp.unlink()
            print("  ✓  04_income_paystub_validation.png")
        else:
            await shot_viewport(page, "04_income_paystub_validation.png")

        await page.set_viewport_size(VIEWPORT)
    else:
        await shot_viewport(page, "04_income_paystub_validation.png")

    # ── Shot 07: W2 + income trend chart ──────────────────────────────────────
    # (Shots 05-06 = static parsed JSON schemas — generated by generate_json_schema_screenshot.py)
    chart_el = page.locator("text=W2 Annual Wages & Taxes").first
    if await chart_el.count():
        await chart_el.scroll_into_view_if_needed()
        await page.wait_for_timeout(1200)
    else:
        await scroll_to(page, 900)
    await shot_viewport(page, "07_income_trend_charts.png")

    # ── Shot 08: AI-generated income intelligence insights ────────────────────
    await go(page, "Income_%26_Tax", wait_ms=3500)
    try:
        await select_person(page, DEMO_PERSON)
    except Exception:
        pass
    await scroll_to(page, 0, settle_ms=500)
    ran = await click_button(page, "Analyze My Income & Taxes")
    if ran:
        # LangGraph runs 6 nodes; allow up to 20 s
        await page.wait_for_timeout(20000)
    await scroll_to(page, 0)
    await shot(page, "08_income_ai_insights.png")


async def act2_spending(page: Page) -> None:
    """
    Act 2 — Spending Tracker
    Full-year 2018 categorised expense list and analytics breakdown.
    """
    print("\nAct 2 — Spending (2018)")

    await go(page, "Spending", wait_ms=5000)
    try:
        await select_person(page, DEMO_PERSON)
    except Exception:
        pass

    # Set date range to full year 2018 so demo spending data shows up.
    # Streamlit date fields use data-testid="stDateInputField" with YYYY/MM/DD text.
    date_fields = page.locator('[data-testid="stDateInputField"]')
    if await date_fields.count() >= 2:
        for idx, val in [(0, "2018/01/01"), (1, "2018/12/31")]:
            fld = date_fields.nth(idx)
            await fld.click(click_count=3)
            await fld.fill(val)
            await fld.press("Enter")
            await page.wait_for_timeout(600)
        # Click Refresh to reload with new dates
        await click_button(page, "Refresh", wait_ms=3000)

    # Shot 09: transaction list — shows 2018 spending rows
    await scroll_to(page, 0)
    await shot(page, "09_spending_transactions.png")

    # Shot 10: analytics tab — pie chart + category breakdown (2018 data)
    analytics_tab = page.get_by_role("tab", name="Analytics")
    if await analytics_tab.count():
        await analytics_tab.click()
        await page.wait_for_timeout(2000)
    else:
        await scroll_bottom(page)
        await page.wait_for_timeout(800)

    # Analytics tab has its own date filters — set to full 2018.
    # Use :visible so we only touch the Analytics fields, not the hidden
    # One-Time Spending date fields that remain in the DOM.
    visible_dates = page.locator('[data-testid="stDateInputField"]:visible')
    for idx, val in enumerate(["2018/01/01", "2018/12/31"]):
        if await visible_dates.count() > idx:
            fld = visible_dates.nth(idx)
            await fld.click(click_count=3)
            await fld.fill(val)
            await fld.press("Tab")          # Tab closes the calendar picker
            await page.wait_for_timeout(400)
    # Dismiss any lingering calendar popup, then wait for Streamlit rerun
    await page.keyboard.press("Escape")
    await page.wait_for_timeout(3000)

    await shot(page, "10_spending_analytics.png")


async def act3_wealth(page: Page) -> None:
    """
    Act 3 — Wealth & Planning
    Asset entry with ownership splits, then the net-worth summary & targets.
    """
    print("\nAct 3 — Wealth & Planning")

    await go(page, "Wealth_%26_Planning", wait_ms=5000)
    try:
        await select_person(page, DEMO_PERSON)
    except Exception:
        pass

    # Shot 11: asset input form (top of page)
    await scroll_to(page, 0)
    await shot(page, "11_wealth_asset_form.png")

    # Shot 12: net-worth summary and target progress (bottom of page)
    await scroll_bottom(page)
    await page.wait_for_timeout(800)
    await shot(page, "12_wealth_summary.png")


async def act4_investing(page: Page) -> None:
    """
    Act 4 — Investing & Trading
    Watchlist UI, curated stock suggestions by sector, index education.
    """
    print("\nAct 4 — Investing & Trading")

    await go(page, "Investing_%26_Trading", wait_ms=6000)
    try:
        await select_person(page, DEMO_PERSON)
        await page.wait_for_timeout(4000)
    except Exception:
        pass

    # Shot 13: watchlist + "Add Stocks" suggestion panel (both columns visible)
    await scroll_to(page, 0)
    await shot(page, "13_investing_watchlist.png")

    # Shot 14: expand the Tech suggestions to show MSFT/AAPL/NVDA etc.
    await expand(page, "Tech")
    await page.wait_for_timeout(800)
    await shot_viewport(page, "14_investing_stock_suggestions.png")

    # Shot 15: index education section
    idx_tab = page.get_by_role("tab", name="Index Education")
    if await idx_tab.count():
        await idx_tab.click()
        await page.wait_for_timeout(1500)
    else:
        await scroll_bottom(page)
        await page.wait_for_timeout(800)
    await shot(page, "15_investing_index_education.png")


async def act5_copilot_conclusion(page: Page) -> None:
    """
    Act 5 — Copilot (Conclusion)
    Ask a plain-English question covering both tax and spending, then capture
    the chat interface showing the question and the AI answer together.
    """
    print("\nAct 5 — Copilot (conclusion)")

    # Navigate to root — Copilot Chat is the default page
    await page.goto(BASE, wait_until="networkidle")
    await page.wait_for_timeout(4000)

    # Shot 14: copilot answering a combined tax + spending question
    textarea = page.locator('[data-testid="stChatInput"] textarea')
    if await textarea.count():
        question = (
            f"For {DEMO_PERSON}: what are the tax optimisation suggestions "
            "based on their income, and what spending categories should they "
            "cut back on to improve savings?"
        )
        await textarea.click()
        await textarea.fill(question)
        await page.wait_for_timeout(300)

        # Click the submit arrow button
        submitted = False
        for selector in [
            '[data-testid="stChatInput"] button[type="submit"]',
            '[data-testid="stChatInputSubmitButton"]',
            '[data-testid="stChatInput"] button',
        ]:
            btn = page.locator(selector)
            if await btn.count():
                await btn.first.click()
                submitted = True
                break

        if not submitted:
            await textarea.press("Enter")

        # Wait for the LangGraph agent to respond (may take up to 30 s)
        await page.wait_for_timeout(30000)
        await scroll_to(page, 0)          # scroll to top so question is visible
        await shot(page, "16_copilot_chat.png")
    else:
        print("  (chat input not found — skipping copilot shot)")
        await shot(page, "16_copilot_chat.png")


# ── main ──────────────────────────────────────────────────────────────────────

async def main() -> None:
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir(parents=True)

    print(f"Output → {OUT_DIR}")
    print("Story: Income pipeline → Spending → Wealth → Investing → Copilot (conclusion)\n")

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=True)
        ctx     = await browser.new_context(viewport=VIEWPORT)
        page    = await ctx.new_page()

        await act1_income_pipeline(page)
        await act2_spending(page)
        await act3_wealth(page)
        await act4_investing(page)
        await act5_copilot_conclusion(page)

        await browser.close()

    count = len(list(OUT_DIR.glob("*.png")))
    print(f"\n✅  Done — {count}/16 screenshots in {OUT_DIR}")
    print("    (shots 05-06 are static — run scripts/generate_json_schema_screenshot.py separately)")


if __name__ == "__main__":
    asyncio.run(main())
